name: Generate CHANGELOG on Merge to Main

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Generate or Update CHANGELOG
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: ./CHANGELOG.md
          release-count: 0
          tag-prefix: ""
          preset: conventionalcommits
          append-git-tag: true
          git-message: "chore(changelog): update CHANGELOG.md after merge to main [skip ci]"
          git-branch: main
          skip-on-empty: false
          skip-tag: true
          skip-version-file: true
          skip-commit: false

      - name: Commit and Push CHANGELOG (if updated)
        run: |
          if [ -f CHANGELOG.md ]; then
            echo "Committing CHANGELOG updates..."
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add CHANGELOG.md
            git commit -m "chore(changelog): update CHANGELOG.md after merge to main [skip ci]" || echo "No changes to commit"
            git push origin main
          else
            echo "CHANGELOG.md not found — skipping commit"
          fi
